from selenium.webdriver.common.by import By

SIGN_IN_BUTTON_LOCATOR = (By.LINK_TEXT, "Sign in")
SIGN_UP_EMAIL_LOCATOR = (By.CSS_SELECTOR, "[name='email_create']")
SIGN_UP_SUBMIT_LOCATOR = (By.XPATH, "//button[@name=\"SubmitCreate\"]")
MALE_LOCATOR = (By.XPATH, "//input[@id='id_gender1']")
FEMALE_LOCATOR = (By.XPATH, "//input[@id='id_gender2']")
CUSTOMER_FIRST_NAME_LOCATOR = (By.NAME, "customer_firstname")
CUSTOMER_LAST_NAME_LOCATOR = (By.NAME, "customer_lastname")
PASSWORD_LOCATOR = (By.ID, "passwd")
FIRSTNAME_LOCATOR = (By.ID, "firstname")
LASTNAME_LOCATOR = (By.ID,  "lastname")
COMPANY_LOCATOR = (By.ID, "company")
ADDRESS_LOCATOR = (By.ID, "address1")
CITY_LOCATOR = (By.ID, "city")
STATE_LOCATOR = (By.NAME, "id_state")
POSTCODE_LOCATOR = (By.NAME, "postcode")
COUNTRY_LOCATOR = (By.NAME, "id_country")
PHONE_NUMBER_LOCATOR = (By.ID, "phone_mobile")
REGISTER_SUBMIT_BUTTON_LOCATOR = (By.NAME, "submitAccount")
SIGNED_USERNAME_LOCATOR = (By.XPATH, "//*[@id=\"header\"]/div[2]/div/div/nav/div[1]/a")
SIGN_UP_FIRST_ERROR_LOCATOR = (By.XPATH, "//*[@class='alert alert-danger']/ol/li[1]")
SIGN_UP_SECOND_ERROR_LOCATOR = (By.XPATH, "//*[@class='alert alert-danger']/ol/li[2]")
SIGN_UP_THIRD_ERROR_LOCATOR = (By.XPATH, "//*[@class='alert alert-danger']/ol/li[3]")
SIGN_UP_FORTH_ERROR_LOCATOR = (By.XPATH, "//*[@class='alert alert-danger']/ol/li[4]")